apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  selector:
    app: flask
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: flask
  type: LoadBalancer
